# 04 - Experimentos CNN

En esta notebook se prueban variaciones de hiperparámetros para CNNs:

- Batch Normalization;
- Dropout;
- Weight Decay;
- Learning Rate;
- Data Augmentation;
- capacidad del modelo.

Primero se realiza un screening rápido usando un solo fold. Luego se corren en validación cruzada completa los mejores candidatos.

El test fijo no se usa en esta notebook.

In [1]:
from pathlib import Path
import os
import sys
import json

import pandas as pd

REPO_ROOT = Path.cwd()

if REPO_ROOT.name == "notebooks":
    REPO_ROOT = REPO_ROOT.parent

os.chdir(REPO_ROOT)

src_path = REPO_ROOT / "src"
if str(src_path) not in sys.path:
    sys.path.append(str(src_path))

from cnn_training import run_cross_validation, save_experiment_outputs

print("Repo root:", REPO_ROOT)

Repo root: c:\Users\tomas\OneDrive\Documentos\MATERIAS ITBA\ELECTIVAS - CUATRIMESTRE X\MACHINE LEARNING y REDES NEURONALES EN BIOINGENIERÍA\skin-dataset-classification

In [2]:
base_config = {
    "mlflow_experiment": "TP_skin_CNN",

    "model": "AlexNetSmall",
    "image_size": 128,
    "batch_size": 32,
    "epochs": 15,
    "lr": 3e-4,
    "optimizer": "adamw",

    "dropout": 0.3,
    "batch_norm": True,
    "weight_decay": 1e-4,
    "augmentation": "light",

    "early_stopping": True,
    "patience": 5,

    "tensorboard": True,
    "mlflow": True,
    "log_pytorch_model": False,
    "histogram_every": 5,

    "seed": 42,
}

In [3]:
screening_configs = []

def make_config(name, **updates):
    cfg = base_config.copy()
    cfg["experiment"] = name
    cfg.update(updates)
    return cfg

screening_configs.append(
    make_config(
        "CNN_SCREEN_1_no_batchnorm",
        batch_norm=False,
    )
)

screening_configs.append(
    make_config(
        "CNN_SCREEN_2_no_dropout",
        dropout=0.0,
    )
)

screening_configs.append(
    make_config(
        "CNN_SCREEN_3_dropout05",
        dropout=0.5,
    )
)

screening_configs.append(
    make_config(
        "CNN_SCREEN_4_aug_minimal",
        augmentation="minimal",
    )
)

screening_configs.append(
    make_config(
        "CNN_SCREEN_5_aug_medium",
        augmentation="medium",
    )
)

screening_configs.append(
    make_config(
        "CNN_SCREEN_6_weight_decay_1e3",
        weight_decay=1e-3,
    )
)

screening_configs.append(
    make_config(
        "CNN_SCREEN_7_lr_1e3",
        lr=1e-3,
    )
)

screening_configs.append(
    make_config(
        "CNN_SCREEN_8_alexnetmedium",
        model="AlexNetMedium",
    )
)

len(screening_configs), [cfg["experiment"] for cfg in screening_configs]

(8,
 ['CNN_SCREEN_1_no_batchnorm',
  'CNN_SCREEN_2_no_dropout',
  'CNN_SCREEN_3_dropout05',
  'CNN_SCREEN_4_aug_minimal',
  'CNN_SCREEN_5_aug_medium',
  'CNN_SCREEN_6_weight_decay_1e3',
  'CNN_SCREEN_7_lr_1e3',
  'CNN_SCREEN_8_alexnetmedium'])

In [4]:
screening_summaries = []

for cfg in screening_configs:
    print("\n" + "=" * 80)
    print("Corriendo:", cfg["experiment"])
    print("=" * 80)

    output = run_cross_validation(
        config=cfg,
        split_csv="data/splits/final_split_5fold.csv",
        folds_to_run=[0],
    )

    output_prefix = cfg["experiment"].lower()
    save_experiment_outputs(
        cv_output=output,
        output_prefix=output_prefix,
    )

    screening_summaries.append(output["summary"])

screening_df = pd.DataFrame(screening_summaries)
screening_df = screening_df.sort_values("val_accuracy_mean", ascending=False)

display(screening_df[[
    "experiment",
    "model",
    "dropout",
    "batch_norm",
    "weight_decay",
    "lr",
    "augmentation",
    "val_accuracy_mean",
    "val_macro_f1_mean",
    "val_balanced_accuracy_mean",
]])

================================================================================
Corriendo: CNN_SCREEN_1_no_batchnorm
================================================================================
Device usado: cpu
Folds a correr: [0]
Clases: {0: 'Actinic keratosis', 1: 'Atopic Dermatitis', 2: 'Benign keratosis', 3: 'Dermatofibroma', 4: 'Melanocytic nevus', 5: 'Melanoma', 6: 'Squamous cell carcinoma', 7: 'Tinea Ringworm Candidiasis', 8: 'Vascular lesion'}
Parámetros entrenables: 2,734,793
[CNN_SCREEN_1_no_batchnorm] fold 0 | epoch 01/15 | train_acc=0.101 | val_acc=0.201 | val_f1=0.103
[CNN_SCREEN_1_no_batchnorm] fold 0 | epoch 02/15 | train_acc=0.216 | val_acc=0.292 | val_f1=0.202
[CNN_SCREEN_1_no_batchnorm] fold 0 | epoch 03/15 | train_acc=0.277 | val_acc=0.285 | val_f1=0.200
[CNN_SCREEN_1_no_batchnorm] fold 0 | epoch 04/15 | train_acc=0.311 | val_acc=0.271 | val_f1=0.180
[CNN_SCREEN_1_no_batchnorm] fold 0 | epoch 05/15 | train_acc=0.323 | val_acc=0.299 | val_f1=0.221
[CNN_SCREEN_1_no_batchnorm] fold 0 | epoch 06/15 | train_acc=0.342 | val_acc=0.361 | val_f1=0.296
[CNN_SCREEN_1_no_batchnorm] fold 0 | epoch 07/15 | train_acc=0.340 | val_acc=0.368 | val_f1=0.288
[CNN_SCREEN_1_no_batchnorm] fold 0 | epoch 08/15 | train_acc=0.379 | val_acc=0.354 | val_f1=0.279
[CNN_SCREEN_1_no_batchnorm] fold 0 | epoch 09/15 | train_acc=0.389 | val_acc=0.396 | val_f1=0.341
[CNN_SCREEN_1_no_batchnorm] fold 0 | epoch 10/15 | train_acc=0.387 | val_acc=0.410 | val_f1=0.340
[CNN_SCREEN_1_no_batchnorm] fold 0 | epoch 11/15 | train_acc=0.387 | val_acc=0.431 | val_f1=0.364
[CNN_SCREEN_1_no_batchnorm] fold 0 | epoch 12/15 | train_acc=0.422 | val_acc=0.472 | val_f1=0.411
[CNN_SCREEN_1_no_batchnorm] fold 0 | epoch 13/15 | train_acc=0.454 | val_acc=0.479 | val_f1=0.439
[CNN_SCREEN_1_no_batchnorm] fold 0 | epoch 14/15 | train_acc=0.487 | val_acc=0.486 | val_f1=0.444
[CNN_SCREEN_1_no_batchnorm] fold 0 | epoch 15/15 | train_acc=0.435 | val_acc=0.472 | val_f1=0.443
Archivos guardados:
- experiments\cnn_screen_1_no_batchnorm_fold_results.csv
- experiments\cnn_screen_1_no_batchnorm_history.csv
- experiments\cnn_screen_1_no_batchnorm_summary.json
- results\training_curves\cnn_screen_1_no_batchnorm_loss.png
- results\training_curves\cnn_screen_1_no_batchnorm_accuracy.png
- results\confusion_matrices\cnn_screen_1_no_batchnorm.png
- results\classification_reports\cnn_screen_1_no_batchnorm_classification_report.txt

================================================================================
Corriendo: CNN_SCREEN_2_no_dropout
================================================================================
Device usado: cpu
Folds a correr: [0]
Clases: {0: 'Actinic keratosis', 1: 'Atopic Dermatitis', 2: 'Benign keratosis', 3: 'Dermatofibroma', 4: 'Melanocytic nevus', 5: 'Melanoma', 6: 'Squamous cell carcinoma', 7: 'Tinea Ringworm Candidiasis', 8: 'Vascular lesion'}
Parámetros entrenables: 2,736,009
[CNN_SCREEN_2_no_dropout] fold 0 | epoch 01/15 | train_acc=0.298 | val_acc=0.361 | val_f1=0.274
[CNN_SCREEN_2_no_dropout] fold 0 | epoch 02/15 | train_acc=0.400 | val_acc=0.444 | val_f1=0.384
[CNN_SCREEN_2_no_dropout] fold 0 | epoch 03/15 | train_acc=0.487 | val_acc=0.507 | val_f1=0.495
[CNN_SCREEN_2_no_dropout] fold 0 | epoch 04/15 | train_acc=0.531 | val_acc=0.542 | val_f1=0.486
[CNN_SCREEN_2_no_dropout] fold 0 | epoch 05/15 | train_acc=0.586 | val_acc=0.576 | val_f1=0.544
[CNN_SCREEN_2_no_dropout] fold 0 | epoch 06/15 | train_acc=0.602 | val_acc=0.618 | val_f1=0.581
[CNN_SCREEN_2_no_dropout] fold 0 | epoch 07/15 | train_acc=0.616 | val_acc=0.562 | val_f1=0.548
[CNN_SCREEN_2_no_dropout] fold 0 | epoch 08/15 | train_acc=0.635 | val_acc=0.611 | val_f1=0.596
[CNN_SCREEN_2_no_dropout] fold 0 | epoch 09/15 | train_acc=0.614 | val_acc=0.583 | val_f1=0.514
[CNN_SCREEN_2_no_dropout] fold 0 | epoch 10/15 | train_acc=0.604 | val_acc=0.583 | val_f1=0.526
[CNN_SCREEN_2_no_dropout] fold 0 | epoch 11/15 | train_acc=0.640 | val_acc=0.583 | val_f1=0.564
Early stopping en fold 0. Mejor epoch: 6, mejor val_acc: 0.618
Archivos guardados:
- experiments\cnn_screen_2_no_dropout_fold_results.csv
- experiments\cnn_screen_2_no_dropout_history.csv
- experiments\cnn_screen_2_no_dropout_summary.json
- results\training_curves\cnn_screen_2_no_dropout_loss.png
- results\training_curves\cnn_screen_2_no_dropout_accuracy.png
- results\confusion_matrices\cnn_screen_2_no_dropout.png
- results\classification_reports\cnn_screen_2_no_dropout_classification_report.txt

================================================================================
Corriendo: CNN_SCREEN_3_dropout05
================================================================================
Device usado: cpu
Folds a correr: [0]
Clases: {0: 'Actinic keratosis', 1: 'Atopic Dermatitis', 2: 'Benign keratosis', 3: 'Dermatofibroma', 4: 'Melanocytic nevus', 5: 'Melanoma', 6: 'Squamous cell carcinoma', 7: 'Tinea Ringworm Candidiasis', 8: 'Vascular lesion'}
Parámetros entrenables: 2,736,009
[CNN_SCREEN_3_dropout05] fold 0 | epoch 01/15 | train_acc=0.185 | val_acc=0.243 | val_f1=0.150
[CNN_SCREEN_3_dropout05] fold 0 | epoch 02/15 | train_acc=0.260 | val_acc=0.493 | val_f1=0.423
[CNN_SCREEN_3_dropout05] fold 0 | epoch 03/15 | train_acc=0.312 | val_acc=0.465 | val_f1=0.409
[CNN_SCREEN_3_dropout05] fold 0 | epoch 04/15 | train_acc=0.368 | val_acc=0.444 | val_f1=0.401
[CNN_SCREEN_3_dropout05] fold 0 | epoch 05/15 | train_acc=0.400 | val_acc=0.507 | val_f1=0.465
[CNN_SCREEN_3_dropout05] fold 0 | epoch 06/15 | train_acc=0.408 | val_acc=0.528 | val_f1=0.479
[CNN_SCREEN_3_dropout05] fold 0 | epoch 07/15 | train_acc=0.459 | val_acc=0.542 | val_f1=0.518
[CNN_SCREEN_3_dropout05] fold 0 | epoch 08/15 | train_acc=0.499 | val_acc=0.514 | val_f1=0.472
[CNN_SCREEN_3_dropout05] fold 0 | epoch 09/15 | train_acc=0.466 | val_acc=0.542 | val_f1=0.501
[CNN_SCREEN_3_dropout05] fold 0 | epoch 10/15 | train_acc=0.452 | val_acc=0.514 | val_f1=0.482
[CNN_SCREEN_3_dropout05] fold 0 | epoch 11/15 | train_acc=0.482 | val_acc=0.514 | val_f1=0.485
[CNN_SCREEN_3_dropout05] fold 0 | epoch 12/15 | train_acc=0.492 | val_acc=0.597 | val_f1=0.552
[CNN_SCREEN_3_dropout05] fold 0 | epoch 13/15 | train_acc=0.527 | val_acc=0.576 | val_f1=0.553
[CNN_SCREEN_3_dropout05] fold 0 | epoch 14/15 | train_acc=0.518 | val_acc=0.618 | val_f1=0.571
[CNN_SCREEN_3_dropout05] fold 0 | epoch 15/15 | train_acc=0.499 | val_acc=0.569 | val_f1=0.528
Archivos guardados:
- experiments\cnn_screen_3_dropout05_fold_results.csv
- experiments\cnn_screen_3_dropout05_history.csv
- experiments\cnn_screen_3_dropout05_summary.json
- results\training_curves\cnn_screen_3_dropout05_loss.png
- results\training_curves\cnn_screen_3_dropout05_accuracy.png
- results\confusion_matrices\cnn_screen_3_dropout05.png
- results\classification_reports\cnn_screen_3_dropout05_classification_report.txt

================================================================================
Corriendo: CNN_SCREEN_4_aug_minimal
================================================================================
Device usado: cpu
Folds a correr: [0]
Clases: {0: 'Actinic keratosis', 1: 'Atopic Dermatitis', 2: 'Benign keratosis', 3: 'Dermatofibroma', 4: 'Melanocytic nevus', 5: 'Melanoma', 6: 'Squamous cell carcinoma', 7: 'Tinea Ringworm Candidiasis', 8: 'Vascular lesion'}
Parámetros entrenables: 2,736,009
[CNN_SCREEN_4_aug_minimal] fold 0 | epoch 01/15 | train_acc=0.243 | val_acc=0.368 | val_f1=0.287
[CNN_SCREEN_4_aug_minimal] fold 0 | epoch 02/15 | train_acc=0.373 | val_acc=0.479 | val_f1=0.426
[CNN_SCREEN_4_aug_minimal] fold 0 | epoch 03/15 | train_acc=0.442 | val_acc=0.549 | val_f1=0.488
[CNN_SCREEN_4_aug_minimal] fold 0 | epoch 04/15 | train_acc=0.517 | val_acc=0.604 | val_f1=0.572
[CNN_SCREEN_4_aug_minimal] fold 0 | epoch 05/15 | train_acc=0.522 | val_acc=0.583 | val_f1=0.535
[CNN_SCREEN_4_aug_minimal] fold 0 | epoch 06/15 | train_acc=0.597 | val_acc=0.597 | val_f1=0.545
[CNN_SCREEN_4_aug_minimal] fold 0 | epoch 07/15 | train_acc=0.609 | val_acc=0.625 | val_f1=0.593
[CNN_SCREEN_4_aug_minimal] fold 0 | epoch 08/15 | train_acc=0.647 | val_acc=0.611 | val_f1=0.588
[CNN_SCREEN_4_aug_minimal] fold 0 | epoch 09/15 | train_acc=0.644 | val_acc=0.618 | val_f1=0.587
[CNN_SCREEN_4_aug_minimal] fold 0 | epoch 10/15 | train_acc=0.667 | val_acc=0.569 | val_f1=0.534
[CNN_SCREEN_4_aug_minimal] fold 0 | epoch 11/15 | train_acc=0.698 | val_acc=0.667 | val_f1=0.640
[CNN_SCREEN_4_aug_minimal] fold 0 | epoch 12/15 | train_acc=0.691 | val_acc=0.646 | val_f1=0.622
[CNN_SCREEN_4_aug_minimal] fold 0 | epoch 13/15 | train_acc=0.712 | val_acc=0.639 | val_f1=0.618
[CNN_SCREEN_4_aug_minimal] fold 0 | epoch 14/15 | train_acc=0.731 | val_acc=0.632 | val_f1=0.616
[CNN_SCREEN_4_aug_minimal] fold 0 | epoch 15/15 | train_acc=0.747 | val_acc=0.646 | val_f1=0.632
Archivos guardados:
- experiments\cnn_screen_4_aug_minimal_fold_results.csv
- experiments\cnn_screen_4_aug_minimal_history.csv
- experiments\cnn_screen_4_aug_minimal_summary.json
- results\training_curves\cnn_screen_4_aug_minimal_loss.png
- results\training_curves\cnn_screen_4_aug_minimal_accuracy.png
- results\confusion_matrices\cnn_screen_4_aug_minimal.png
- results\classification_reports\cnn_screen_4_aug_minimal_classification_report.txt

================================================================================
Corriendo: CNN_SCREEN_5_aug_medium
================================================================================
Device usado: cpu
Folds a correr: [0]
Clases: {0: 'Actinic keratosis', 1: 'Atopic Dermatitis', 2: 'Benign keratosis', 3: 'Dermatofibroma', 4: 'Melanocytic nevus', 5: 'Melanoma', 6: 'Squamous cell carcinoma', 7: 'Tinea Ringworm Candidiasis', 8: 'Vascular lesion'}
Parámetros entrenables: 2,736,009
[CNN_SCREEN_5_aug_medium] fold 0 | epoch 01/15 | train_acc=0.197 | val_acc=0.250 | val_f1=0.164
[CNN_SCREEN_5_aug_medium] fold 0 | epoch 02/15 | train_acc=0.326 | val_acc=0.417 | val_f1=0.334
[CNN_SCREEN_5_aug_medium] fold 0 | epoch 03/15 | train_acc=0.382 | val_acc=0.486 | val_f1=0.402
[CNN_SCREEN_5_aug_medium] fold 0 | epoch 04/15 | train_acc=0.438 | val_acc=0.500 | val_f1=0.460
[CNN_SCREEN_5_aug_medium] fold 0 | epoch 05/15 | train_acc=0.461 | val_acc=0.569 | val_f1=0.527
[CNN_SCREEN_5_aug_medium] fold 0 | epoch 06/15 | train_acc=0.426 | val_acc=0.479 | val_f1=0.439
[CNN_SCREEN_5_aug_medium] fold 0 | epoch 07/15 | train_acc=0.501 | val_acc=0.569 | val_f1=0.541
[CNN_SCREEN_5_aug_medium] fold 0 | epoch 08/15 | train_acc=0.464 | val_acc=0.493 | val_f1=0.444
[CNN_SCREEN_5_aug_medium] fold 0 | epoch 09/15 | train_acc=0.445 | val_acc=0.618 | val_f1=0.585
[CNN_SCREEN_5_aug_medium] fold 0 | epoch 10/15 | train_acc=0.475 | val_acc=0.611 | val_f1=0.572
[CNN_SCREEN_5_aug_medium] fold 0 | epoch 11/15 | train_acc=0.504 | val_acc=0.535 | val_f1=0.479
[CNN_SCREEN_5_aug_medium] fold 0 | epoch 12/15 | train_acc=0.504 | val_acc=0.549 | val_f1=0.492
[CNN_SCREEN_5_aug_medium] fold 0 | epoch 13/15 | train_acc=0.524 | val_acc=0.535 | val_f1=0.507
[CNN_SCREEN_5_aug_medium] fold 0 | epoch 14/15 | train_acc=0.513 | val_acc=0.569 | val_f1=0.535
Early stopping en fold 0. Mejor epoch: 9, mejor val_acc: 0.618
Archivos guardados:
- experiments\cnn_screen_5_aug_medium_fold_results.csv
- experiments\cnn_screen_5_aug_medium_history.csv
- experiments\cnn_screen_5_aug_medium_summary.json
- results\training_curves\cnn_screen_5_aug_medium_loss.png
- results\training_curves\cnn_screen_5_aug_medium_accuracy.png
- results\confusion_matrices\cnn_screen_5_aug_medium.png
- results\classification_reports\cnn_screen_5_aug_medium_classification_report.txt

================================================================================
Corriendo: CNN_SCREEN_6_weight_decay_1e3
================================================================================
Device usado: cpu
Folds a correr: [0]
Clases: {0: 'Actinic keratosis', 1: 'Atopic Dermatitis', 2: 'Benign keratosis', 3: 'Dermatofibroma', 4: 'Melanocytic nevus', 5: 'Melanoma', 6: 'Squamous cell carcinoma', 7: 'Tinea Ringworm Candidiasis', 8: 'Vascular lesion'}
Parámetros entrenables: 2,736,009
[CNN_SCREEN_6_weight_decay_1e3] fold 0 | epoch 01/15 | train_acc=0.215 | val_acc=0.347 | val_f1=0.267
[CNN_SCREEN_6_weight_decay_1e3] fold 0 | epoch 02/15 | train_acc=0.321 | val_acc=0.438 | val_f1=0.359
[CNN_SCREEN_6_weight_decay_1e3] fold 0 | epoch 03/15 | train_acc=0.394 | val_acc=0.354 | val_f1=0.293
[CNN_SCREEN_6_weight_decay_1e3] fold 0 | epoch 04/15 | train_acc=0.468 | val_acc=0.472 | val_f1=0.437
[CNN_SCREEN_6_weight_decay_1e3] fold 0 | epoch 05/15 | train_acc=0.473 | val_acc=0.590 | val_f1=0.561
[CNN_SCREEN_6_weight_decay_1e3] fold 0 | epoch 06/15 | train_acc=0.515 | val_acc=0.583 | val_f1=0.538
[CNN_SCREEN_6_weight_decay_1e3] fold 0 | epoch 07/15 | train_acc=0.511 | val_acc=0.639 | val_f1=0.596
[CNN_SCREEN_6_weight_decay_1e3] fold 0 | epoch 08/15 | train_acc=0.538 | val_acc=0.556 | val_f1=0.528
[CNN_SCREEN_6_weight_decay_1e3] fold 0 | epoch 09/15 | train_acc=0.569 | val_acc=0.583 | val_f1=0.540
[CNN_SCREEN_6_weight_decay_1e3] fold 0 | epoch 10/15 | train_acc=0.558 | val_acc=0.562 | val_f1=0.545
[CNN_SCREEN_6_weight_decay_1e3] fold 0 | epoch 11/15 | train_acc=0.558 | val_acc=0.618 | val_f1=0.588
[CNN_SCREEN_6_weight_decay_1e3] fold 0 | epoch 12/15 | train_acc=0.599 | val_acc=0.611 | val_f1=0.589
Early stopping en fold 0. Mejor epoch: 7, mejor val_acc: 0.639
Archivos guardados:
- experiments\cnn_screen_6_weight_decay_1e3_fold_results.csv
- experiments\cnn_screen_6_weight_decay_1e3_history.csv
- experiments\cnn_screen_6_weight_decay_1e3_summary.json
- results\training_curves\cnn_screen_6_weight_decay_1e3_loss.png
- results\training_curves\cnn_screen_6_weight_decay_1e3_accuracy.png
- results\confusion_matrices\cnn_screen_6_weight_decay_1e3.png
- results\classification_reports\cnn_screen_6_weight_decay_1e3_classification_report.txt

================================================================================
Corriendo: CNN_SCREEN_7_lr_1e3
================================================================================
Device usado: cpu
Folds a correr: [0]
Clases: {0: 'Actinic keratosis', 1: 'Atopic Dermatitis', 2: 'Benign keratosis', 3: 'Dermatofibroma', 4: 'Melanocytic nevus', 5: 'Melanoma', 6: 'Squamous cell carcinoma', 7: 'Tinea Ringworm Candidiasis', 8: 'Vascular lesion'}
Parámetros entrenables: 2,736,009
[CNN_SCREEN_7_lr_1e3] fold 0 | epoch 01/15 | train_acc=0.218 | val_acc=0.340 | val_f1=0.214
[CNN_SCREEN_7_lr_1e3] fold 0 | epoch 02/15 | train_acc=0.281 | val_acc=0.424 | val_f1=0.336
[CNN_SCREEN_7_lr_1e3] fold 0 | epoch 03/15 | train_acc=0.335 | val_acc=0.444 | val_f1=0.380
[CNN_SCREEN_7_lr_1e3] fold 0 | epoch 04/15 | train_acc=0.396 | val_acc=0.479 | val_f1=0.406
[CNN_SCREEN_7_lr_1e3] fold 0 | epoch 05/15 | train_acc=0.447 | val_acc=0.535 | val_f1=0.478
[CNN_SCREEN_7_lr_1e3] fold 0 | epoch 06/15 | train_acc=0.447 | val_acc=0.521 | val_f1=0.505
[CNN_SCREEN_7_lr_1e3] fold 0 | epoch 07/15 | train_acc=0.457 | val_acc=0.472 | val_f1=0.412
[CNN_SCREEN_7_lr_1e3] fold 0 | epoch 08/15 | train_acc=0.496 | val_acc=0.542 | val_f1=0.492
[CNN_SCREEN_7_lr_1e3] fold 0 | epoch 09/15 | train_acc=0.503 | val_acc=0.583 | val_f1=0.538
[CNN_SCREEN_7_lr_1e3] fold 0 | epoch 10/15 | train_acc=0.487 | val_acc=0.514 | val_f1=0.483
[CNN_SCREEN_7_lr_1e3] fold 0 | epoch 11/15 | train_acc=0.534 | val_acc=0.569 | val_f1=0.506
[CNN_SCREEN_7_lr_1e3] fold 0 | epoch 12/15 | train_acc=0.565 | val_acc=0.549 | val_f1=0.524
[CNN_SCREEN_7_lr_1e3] fold 0 | epoch 13/15 | train_acc=0.597 | val_acc=0.562 | val_f1=0.537
[CNN_SCREEN_7_lr_1e3] fold 0 | epoch 14/15 | train_acc=0.551 | val_acc=0.542 | val_f1=0.483
Early stopping en fold 0. Mejor epoch: 9, mejor val_acc: 0.583
Archivos guardados:
- experiments\cnn_screen_7_lr_1e3_fold_results.csv
- experiments\cnn_screen_7_lr_1e3_history.csv
- experiments\cnn_screen_7_lr_1e3_summary.json
- results\training_curves\cnn_screen_7_lr_1e3_loss.png
- results\training_curves\cnn_screen_7_lr_1e3_accuracy.png
- results\confusion_matrices\cnn_screen_7_lr_1e3.png
- results\classification_reports\cnn_screen_7_lr_1e3_classification_report.txt

================================================================================
Corriendo: CNN_SCREEN_8_alexnetmedium
================================================================================
Device usado: cpu
Folds a correr: [0]
Clases: {0: 'Actinic keratosis', 1: 'Atopic Dermatitis', 2: 'Benign keratosis', 3: 'Dermatofibroma', 4: 'Melanocytic nevus', 5: 'Melanoma', 6: 'Squamous cell carcinoma', 7: 'Tinea Ringworm Candidiasis', 8: 'Vascular lesion'}
Parámetros entrenables: 6,457,097
[CNN_SCREEN_8_alexnetmedium] fold 0 | epoch 01/15 | train_acc=0.230 | val_acc=0.319 | val_f1=0.211
[CNN_SCREEN_8_alexnetmedium] fold 0 | epoch 02/15 | train_acc=0.328 | val_acc=0.451 | val_f1=0.392
[CNN_SCREEN_8_alexnetmedium] fold 0 | epoch 03/15 | train_acc=0.421 | val_acc=0.368 | val_f1=0.349
[CNN_SCREEN_8_alexnetmedium] fold 0 | epoch 04/15 | train_acc=0.450 | val_acc=0.472 | val_f1=0.422
[CNN_SCREEN_8_alexnetmedium] fold 0 | epoch 05/15 | train_acc=0.494 | val_acc=0.479 | val_f1=0.453
[CNN_SCREEN_8_alexnetmedium] fold 0 | epoch 06/15 | train_acc=0.527 | val_acc=0.542 | val_f1=0.505
[CNN_SCREEN_8_alexnetmedium] fold 0 | epoch 07/15 | train_acc=0.518 | val_acc=0.521 | val_f1=0.482
[CNN_SCREEN_8_alexnetmedium] fold 0 | epoch 08/15 | train_acc=0.534 | val_acc=0.569 | val_f1=0.563
[CNN_SCREEN_8_alexnetmedium] fold 0 | epoch 09/15 | train_acc=0.531 | val_acc=0.549 | val_f1=0.529
[CNN_SCREEN_8_alexnetmedium] fold 0 | epoch 10/15 | train_acc=0.546 | val_acc=0.556 | val_f1=0.526
[CNN_SCREEN_8_alexnetmedium] fold 0 | epoch 11/15 | train_acc=0.600 | val_acc=0.618 | val_f1=0.587
[CNN_SCREEN_8_alexnetmedium] fold 0 | epoch 12/15 | train_acc=0.567 | val_acc=0.549 | val_f1=0.516
[CNN_SCREEN_8_alexnetmedium] fold 0 | epoch 13/15 | train_acc=0.625 | val_acc=0.611 | val_f1=0.571
[CNN_SCREEN_8_alexnetmedium] fold 0 | epoch 14/15 | train_acc=0.599 | val_acc=0.549 | val_f1=0.522
[CNN_SCREEN_8_alexnetmedium] fold 0 | epoch 15/15 | train_acc=0.620 | val_acc=0.604 | val_f1=0.569
Archivos guardados:
- experiments\cnn_screen_8_alexnetmedium_fold_results.csv
- experiments\cnn_screen_8_alexnetmedium_history.csv
- experiments\cnn_screen_8_alexnetmedium_summary.json
- results\training_curves\cnn_screen_8_alexnetmedium_loss.png
- results\training_curves\cnn_screen_8_alexnetmedium_accuracy.png
- results\confusion_matrices\cnn_screen_8_alexnetmedium.png
- results\classification_reports\cnn_screen_8_alexnetmedium_classification_report.txt

,experiment,model,dropout,batch_norm,weight_decay,lr,augmentation,val_accuracy_mean,val_macro_f1_mean,val_balanced_accuracy_mean
3,CNN_SCREEN_4_aug_minimal,AlexNetSmall,0.3,True,0.0001,0.0003,minimal,0.666667,0.639821,0.651515
5,CNN_SCREEN_6_weight_decay_1e3,AlexNetSmall,0.3,True,0.0010,0.0003,light,0.638889,0.595755,0.616713
2,CNN_SCREEN_3_dropout05,AlexNetSmall,0.5,True,0.0001,0.0003,light,0.618056,0.570922,0.592904
1,CNN_SCREEN_2_no_dropout,AlexNetSmall,0.0,True,0.0001,0.0003,light,0.618056,0.581046,0.598633
7,CNN_SCREEN_8_alexnetmedium,AlexNetMedium,0.3,True,0.0001,0.0003,light,0.618056,0.587294,0.597233
4,CNN_SCREEN_5_aug_medium,AlexNetSmall,0.3,True,0.0001,0.0003,medium,0.618056,0.585323,0.597869
6,CNN_SCREEN_7_lr_1e3,AlexNetSmall,0.3,True,0.0001,0.0010,light,0.583333,0.537774,0.573720
0,CNN_SCREEN_1_no_batchnorm,AlexNetSmall,0.3,False,0.0001,0.0003,light,0.486111,0.444009,0.467320

In [5]:
screening_summary_path = Path("experiments/cnn_screening_summary.csv")
screening_df.to_csv(screening_summary_path, index=False)
print("Guardado:", screening_summary_path)

Guardado: experiments\cnn_screening_summary.csv

In [6]:
top2_names = screening_df.head(2)["experiment"].tolist()
top2_names

top2_screening_configs = [
    cfg for cfg in screening_configs
    if cfg["experiment"] in top2_names
]

top2_screening_configs

[{'mlflow_experiment': 'TP_skin_CNN',
  'model': 'AlexNetSmall',
  'image_size': 128,
  'batch_size': 32,
  'epochs': 15,
  'lr': 0.0003,
  'optimizer': 'adamw',
  'dropout': 0.3,
  'batch_norm': True,
  'weight_decay': 0.0001,
  'augmentation': 'minimal',
  'early_stopping': True,
  'patience': 5,
  'tensorboard': True,
  'mlflow': True,
  'log_pytorch_model': False,
  'histogram_every': 5,
  'seed': 42,
  'experiment': 'CNN_SCREEN_4_aug_minimal'},
 {'mlflow_experiment': 'TP_skin_CNN',
  'model': 'AlexNetSmall',
  'image_size': 128,
  'batch_size': 32,
  'epochs': 15,
  'lr': 0.0003,
  'optimizer': 'adamw',
  'dropout': 0.3,
  'batch_norm': True,
  'weight_decay': 0.001,
  'augmentation': 'light',
  'early_stopping': True,
  'patience': 5,
  'tensorboard': True,
  'mlflow': True,
  'log_pytorch_model': False,
  'histogram_every': 5,
  'seed': 42,
  'experiment': 'CNN_SCREEN_6_weight_decay_1e3'}]

In [7]:
full_summaries = []

for cfg in top2_screening_configs:
    full_cfg = cfg.copy()

    full_cfg["experiment"] = cfg["experiment"].replace("CNN_SCREEN_", "CNN_FULL_")
    full_cfg["epochs"] = 25
    full_cfg["patience"] = 6
    full_cfg["log_pytorch_model"] = True

    print("\n" + "=" * 80)
    print("Corriendo FULL CV:", full_cfg["experiment"])
    print("=" * 80)

    output = run_cross_validation(
        config=full_cfg,
        split_csv="data/splits/final_split_5fold.csv",
        folds_to_run=None,
    )

    output_prefix = full_cfg["experiment"].lower()
    save_experiment_outputs(
        cv_output=output,
        output_prefix=output_prefix,
    )

    full_summaries.append(output["summary"])

full_df = pd.DataFrame(full_summaries)
full_df = full_df.sort_values("val_accuracy_mean", ascending=False)

display(full_df[[
    "experiment",
    "model",
    "dropout",
    "batch_norm",
    "weight_decay",
    "lr",
    "augmentation",
    "val_accuracy_mean",
    "val_accuracy_std",
    "val_macro_f1_mean",
    "val_balanced_accuracy_mean",
]])

================================================================================
Corriendo FULL CV: CNN_FULL_4_aug_minimal
================================================================================
Device usado: cpu
Folds a correr: [0, 1, 2, 3, 4]
Clases: {0: 'Actinic keratosis', 1: 'Atopic Dermatitis', 2: 'Benign keratosis', 3: 'Dermatofibroma', 4: 'Melanocytic nevus', 5: 'Melanoma', 6: 'Squamous cell carcinoma', 7: 'Tinea Ringworm Candidiasis', 8: 'Vascular lesion'}
Parámetros entrenables: 2,736,009
[CNN_FULL_4_aug_minimal] fold 0 | epoch 01/25 | train_acc=0.243 | val_acc=0.368 | val_f1=0.287
[CNN_FULL_4_aug_minimal] fold 0 | epoch 02/25 | train_acc=0.373 | val_acc=0.479 | val_f1=0.426
[CNN_FULL_4_aug_minimal] fold 0 | epoch 03/25 | train_acc=0.442 | val_acc=0.549 | val_f1=0.488
[CNN_FULL_4_aug_minimal] fold 0 | epoch 04/25 | train_acc=0.517 | val_acc=0.604 | val_f1=0.572
[CNN_FULL_4_aug_minimal] fold 0 | epoch 05/25 | train_acc=0.522 | val_acc=0.583 | val_f1=0.535
[CNN_FULL_4_aug_minimal] fold 0 | epoch 06/25 | train_acc=0.597 | val_acc=0.597 | val_f1=0.545
[CNN_FULL_4_aug_minimal] fold 0 | epoch 07/25 | train_acc=0.609 | val_acc=0.625 | val_f1=0.593
[CNN_FULL_4_aug_minimal] fold 0 | epoch 08/25 | train_acc=0.647 | val_acc=0.611 | val_f1=0.588
[CNN_FULL_4_aug_minimal] fold 0 | epoch 09/25 | train_acc=0.644 | val_acc=0.618 | val_f1=0.587
[CNN_FULL_4_aug_minimal] fold 0 | epoch 10/25 | train_acc=0.667 | val_acc=0.569 | val_f1=0.534
[CNN_FULL_4_aug_minimal] fold 0 | epoch 11/25 | train_acc=0.698 | val_acc=0.667 | val_f1=0.640
[CNN_FULL_4_aug_minimal] fold 0 | epoch 12/25 | train_acc=0.691 | val_acc=0.646 | val_f1=0.622
[CNN_FULL_4_aug_minimal] fold 0 | epoch 13/25 | train_acc=0.712 | val_acc=0.639 | val_f1=0.618
[CNN_FULL_4_aug_minimal] fold 0 | epoch 14/25 | train_acc=0.731 | val_acc=0.632 | val_f1=0.616
[CNN_FULL_4_aug_minimal] fold 0 | epoch 15/25 | train_acc=0.747 | val_acc=0.646 | val_f1=0.632
[CNN_FULL_4_aug_minimal] fold 0 | epoch 16/25 | train_acc=0.763 | val_acc=0.694 | val_f1=0.679
[CNN_FULL_4_aug_minimal] fold 0 | epoch 17/25 | train_acc=0.759 | val_acc=0.660 | val_f1=0.649
[CNN_FULL_4_aug_minimal] fold 0 | epoch 18/25 | train_acc=0.805 | val_acc=0.632 | val_f1=0.632
[CNN_FULL_4_aug_minimal] fold 0 | epoch 19/25 | train_acc=0.824 | val_acc=0.694 | val_f1=0.677
[CNN_FULL_4_aug_minimal] fold 0 | epoch 20/25 | train_acc=0.829 | val_acc=0.583 | val_f1=0.572
[CNN_FULL_4_aug_minimal] fold 0 | epoch 21/25 | train_acc=0.838 | val_acc=0.639 | val_f1=0.632
[CNN_FULL_4_aug_minimal] fold 0 | epoch 22/25 | train_acc=0.848 | val_acc=0.653 | val_f1=0.635
Early stopping en fold 0. Mejor epoch: 16, mejor val_acc: 0.694
[CNN_FULL_4_aug_minimal] fold 1 | epoch 01/25 | train_acc=0.243 | val_acc=0.285 | val_f1=0.231
[CNN_FULL_4_aug_minimal] fold 1 | epoch 02/25 | train_acc=0.361 | val_acc=0.438 | val_f1=0.391
[CNN_FULL_4_aug_minimal] fold 1 | epoch 03/25 | train_acc=0.459 | val_acc=0.403 | val_f1=0.375
[CNN_FULL_4_aug_minimal] fold 1 | epoch 04/25 | train_acc=0.503 | val_acc=0.556 | val_f1=0.521
[CNN_FULL_4_aug_minimal] fold 1 | epoch 05/25 | train_acc=0.551 | val_acc=0.569 | val_f1=0.541
[CNN_FULL_4_aug_minimal] fold 1 | epoch 06/25 | train_acc=0.539 | val_acc=0.597 | val_f1=0.593
[CNN_FULL_4_aug_minimal] fold 1 | epoch 07/25 | train_acc=0.551 | val_acc=0.535 | val_f1=0.521
[CNN_FULL_4_aug_minimal] fold 1 | epoch 08/25 | train_acc=0.613 | val_acc=0.569 | val_f1=0.541
[CNN_FULL_4_aug_minimal] fold 1 | epoch 09/25 | train_acc=0.614 | val_acc=0.639 | val_f1=0.632
[CNN_FULL_4_aug_minimal] fold 1 | epoch 10/25 | train_acc=0.614 | val_acc=0.618 | val_f1=0.625
[CNN_FULL_4_aug_minimal] fold 1 | epoch 11/25 | train_acc=0.651 | val_acc=0.653 | val_f1=0.648
[CNN_FULL_4_aug_minimal] fold 1 | epoch 12/25 | train_acc=0.670 | val_acc=0.639 | val_f1=0.648
[CNN_FULL_4_aug_minimal] fold 1 | epoch 13/25 | train_acc=0.703 | val_acc=0.611 | val_f1=0.610
[CNN_FULL_4_aug_minimal] fold 1 | epoch 14/25 | train_acc=0.670 | val_acc=0.590 | val_f1=0.584
[CNN_FULL_4_aug_minimal] fold 1 | epoch 15/25 | train_acc=0.726 | val_acc=0.646 | val_f1=0.628
[CNN_FULL_4_aug_minimal] fold 1 | epoch 16/25 | train_acc=0.754 | val_acc=0.660 | val_f1=0.671
[CNN_FULL_4_aug_minimal] fold 1 | epoch 17/25 | train_acc=0.735 | val_acc=0.646 | val_f1=0.649
[CNN_FULL_4_aug_minimal] fold 1 | epoch 18/25 | train_acc=0.752 | val_acc=0.688 | val_f1=0.692
[CNN_FULL_4_aug_minimal] fold 1 | epoch 19/25 | train_acc=0.771 | val_acc=0.639 | val_f1=0.638
[CNN_FULL_4_aug_minimal] fold 1 | epoch 20/25 | train_acc=0.803 | val_acc=0.660 | val_f1=0.660
[CNN_FULL_4_aug_minimal] fold 1 | epoch 21/25 | train_acc=0.791 | val_acc=0.694 | val_f1=0.688
[CNN_FULL_4_aug_minimal] fold 1 | epoch 22/25 | train_acc=0.810 | val_acc=0.708 | val_f1=0.701
[CNN_FULL_4_aug_minimal] fold 1 | epoch 23/25 | train_acc=0.827 | val_acc=0.660 | val_f1=0.671
[CNN_FULL_4_aug_minimal] fold 1 | epoch 24/25 | train_acc=0.831 | val_acc=0.674 | val_f1=0.661
[CNN_FULL_4_aug_minimal] fold 1 | epoch 25/25 | train_acc=0.855 | val_acc=0.653 | val_f1=0.650
[CNN_FULL_4_aug_minimal] fold 2 | epoch 01/25 | train_acc=0.251 | val_acc=0.329 | val_f1=0.264
[CNN_FULL_4_aug_minimal] fold 2 | epoch 02/25 | train_acc=0.369 | val_acc=0.455 | val_f1=0.394
[CNN_FULL_4_aug_minimal] fold 2 | epoch 03/25 | train_acc=0.491 | val_acc=0.503 | val_f1=0.487
[CNN_FULL_4_aug_minimal] fold 2 | epoch 04/25 | train_acc=0.537 | val_acc=0.580 | val_f1=0.565
[CNN_FULL_4_aug_minimal] fold 2 | epoch 05/25 | train_acc=0.592 | val_acc=0.580 | val_f1=0.566
[CNN_FULL_4_aug_minimal] fold 2 | epoch 06/25 | train_acc=0.580 | val_acc=0.594 | val_f1=0.581
[CNN_FULL_4_aug_minimal] fold 2 | epoch 07/25 | train_acc=0.580 | val_acc=0.566 | val_f1=0.564
[CNN_FULL_4_aug_minimal] fold 2 | epoch 08/25 | train_acc=0.620 | val_acc=0.629 | val_f1=0.619
[CNN_FULL_4_aug_minimal] fold 2 | epoch 09/25 | train_acc=0.622 | val_acc=0.608 | val_f1=0.579
[CNN_FULL_4_aug_minimal] fold 2 | epoch 10/25 | train_acc=0.683 | val_acc=0.608 | val_f1=0.587
[CNN_FULL_4_aug_minimal] fold 2 | epoch 11/25 | train_acc=0.706 | val_acc=0.566 | val_f1=0.556
[CNN_FULL_4_aug_minimal] fold 2 | epoch 12/25 | train_acc=0.678 | val_acc=0.573 | val_f1=0.553
[CNN_FULL_4_aug_minimal] fold 2 | epoch 13/25 | train_acc=0.728 | val_acc=0.643 | val_f1=0.647
[CNN_FULL_4_aug_minimal] fold 2 | epoch 14/25 | train_acc=0.720 | val_acc=0.622 | val_f1=0.609
[CNN_FULL_4_aug_minimal] fold 2 | epoch 15/25 | train_acc=0.726 | val_acc=0.573 | val_f1=0.581
[CNN_FULL_4_aug_minimal] fold 2 | epoch 16/25 | train_acc=0.725 | val_acc=0.629 | val_f1=0.622
[CNN_FULL_4_aug_minimal] fold 2 | epoch 17/25 | train_acc=0.777 | val_acc=0.615 | val_f1=0.594
[CNN_FULL_4_aug_minimal] fold 2 | epoch 18/25 | train_acc=0.780 | val_acc=0.664 | val_f1=0.664
[CNN_FULL_4_aug_minimal] fold 2 | epoch 19/25 | train_acc=0.805 | val_acc=0.587 | val_f1=0.588
[CNN_FULL_4_aug_minimal] fold 2 | epoch 20/25 | train_acc=0.801 | val_acc=0.636 | val_f1=0.619
[CNN_FULL_4_aug_minimal] fold 2 | epoch 21/25 | train_acc=0.829 | val_acc=0.601 | val_f1=0.594
[CNN_FULL_4_aug_minimal] fold 2 | epoch 22/25 | train_acc=0.831 | val_acc=0.650 | val_f1=0.637
[CNN_FULL_4_aug_minimal] fold 2 | epoch 23/25 | train_acc=0.814 | val_acc=0.615 | val_f1=0.602
[CNN_FULL_4_aug_minimal] fold 2 | epoch 24/25 | train_acc=0.826 | val_acc=0.608 | val_f1=0.590
Early stopping en fold 2. Mejor epoch: 18, mejor val_acc: 0.664
[CNN_FULL_4_aug_minimal] fold 3 | epoch 01/25 | train_acc=0.232 | val_acc=0.357 | val_f1=0.249
[CNN_FULL_4_aug_minimal] fold 3 | epoch 02/25 | train_acc=0.392 | val_acc=0.420 | val_f1=0.378
[CNN_FULL_4_aug_minimal] fold 3 | epoch 03/25 | train_acc=0.443 | val_acc=0.392 | val_f1=0.338
[CNN_FULL_4_aug_minimal] fold 3 | epoch 04/25 | train_acc=0.535 | val_acc=0.538 | val_f1=0.497
[CNN_FULL_4_aug_minimal] fold 3 | epoch 05/25 | train_acc=0.592 | val_acc=0.545 | val_f1=0.530
[CNN_FULL_4_aug_minimal] fold 3 | epoch 06/25 | train_acc=0.561 | val_acc=0.552 | val_f1=0.514
[CNN_FULL_4_aug_minimal] fold 3 | epoch 07/25 | train_acc=0.599 | val_acc=0.594 | val_f1=0.579
[CNN_FULL_4_aug_minimal] fold 3 | epoch 08/25 | train_acc=0.639 | val_acc=0.594 | val_f1=0.564
[CNN_FULL_4_aug_minimal] fold 3 | epoch 09/25 | train_acc=0.659 | val_acc=0.629 | val_f1=0.609
[CNN_FULL_4_aug_minimal] fold 3 | epoch 10/25 | train_acc=0.674 | val_acc=0.650 | val_f1=0.640
[CNN_FULL_4_aug_minimal] fold 3 | epoch 11/25 | train_acc=0.704 | val_acc=0.636 | val_f1=0.619
[CNN_FULL_4_aug_minimal] fold 3 | epoch 12/25 | train_acc=0.681 | val_acc=0.608 | val_f1=0.591
[CNN_FULL_4_aug_minimal] fold 3 | epoch 13/25 | train_acc=0.709 | val_acc=0.636 | val_f1=0.639
[CNN_FULL_4_aug_minimal] fold 3 | epoch 14/25 | train_acc=0.733 | val_acc=0.643 | val_f1=0.635
[CNN_FULL_4_aug_minimal] fold 3 | epoch 15/25 | train_acc=0.779 | val_acc=0.615 | val_f1=0.607
[CNN_FULL_4_aug_minimal] fold 3 | epoch 16/25 | train_acc=0.768 | val_acc=0.622 | val_f1=0.627
Early stopping en fold 3. Mejor epoch: 10, mejor val_acc: 0.650
[CNN_FULL_4_aug_minimal] fold 4 | epoch 01/25 | train_acc=0.263 | val_acc=0.357 | val_f1=0.308
[CNN_FULL_4_aug_minimal] fold 4 | epoch 02/25 | train_acc=0.371 | val_acc=0.434 | val_f1=0.390
[CNN_FULL_4_aug_minimal] fold 4 | epoch 03/25 | train_acc=0.451 | val_acc=0.503 | val_f1=0.453
[CNN_FULL_4_aug_minimal] fold 4 | epoch 04/25 | train_acc=0.512 | val_acc=0.538 | val_f1=0.490
[CNN_FULL_4_aug_minimal] fold 4 | epoch 05/25 | train_acc=0.585 | val_acc=0.552 | val_f1=0.531
[CNN_FULL_4_aug_minimal] fold 4 | epoch 06/25 | train_acc=0.573 | val_acc=0.594 | val_f1=0.565
[CNN_FULL_4_aug_minimal] fold 4 | epoch 07/25 | train_acc=0.599 | val_acc=0.552 | val_f1=0.548
[CNN_FULL_4_aug_minimal] fold 4 | epoch 08/25 | train_acc=0.603 | val_acc=0.622 | val_f1=0.595
[CNN_FULL_4_aug_minimal] fold 4 | epoch 09/25 | train_acc=0.631 | val_acc=0.552 | val_f1=0.550
[CNN_FULL_4_aug_minimal] fold 4 | epoch 10/25 | train_acc=0.713 | val_acc=0.601 | val_f1=0.607
[CNN_FULL_4_aug_minimal] fold 4 | epoch 11/25 | train_acc=0.672 | val_acc=0.629 | val_f1=0.610
[CNN_FULL_4_aug_minimal] fold 4 | epoch 12/25 | train_acc=0.683 | val_acc=0.608 | val_f1=0.595
[CNN_FULL_4_aug_minimal] fold 4 | epoch 13/25 | train_acc=0.730 | val_acc=0.594 | val_f1=0.594
[CNN_FULL_4_aug_minimal] fold 4 | epoch 14/25 | train_acc=0.749 | val_acc=0.650 | val_f1=0.658
[CNN_FULL_4_aug_minimal] fold 4 | epoch 15/25 | train_acc=0.763 | val_acc=0.622 | val_f1=0.631
[CNN_FULL_4_aug_minimal] fold 4 | epoch 16/25 | train_acc=0.782 | val_acc=0.615 | val_f1=0.619
[CNN_FULL_4_aug_minimal] fold 4 | epoch 17/25 | train_acc=0.794 | val_acc=0.643 | val_f1=0.645
[CNN_FULL_4_aug_minimal] fold 4 | epoch 18/25 | train_acc=0.784 | val_acc=0.650 | val_f1=0.645
[CNN_FULL_4_aug_minimal] fold 4 | epoch 19/25 | train_acc=0.780 | val_acc=0.657 | val_f1=0.669
[CNN_FULL_4_aug_minimal] fold 4 | epoch 20/25 | train_acc=0.803 | val_acc=0.678 | val_f1=0.685
[CNN_FULL_4_aug_minimal] fold 4 | epoch 21/25 | train_acc=0.812 | val_acc=0.657 | val_f1=0.654
[CNN_FULL_4_aug_minimal] fold 4 | epoch 22/25 | train_acc=0.803 | val_acc=0.629 | val_f1=0.633
[CNN_FULL_4_aug_minimal] fold 4 | epoch 23/25 | train_acc=0.852 | val_acc=0.657 | val_f1=0.660
[CNN_FULL_4_aug_minimal] fold 4 | epoch 24/25 | train_acc=0.852 | val_acc=0.650 | val_f1=0.657
[CNN_FULL_4_aug_minimal] fold 4 | epoch 25/25 | train_acc=0.859 | val_acc=0.664 | val_f1=0.663

2026/06/18 10:57:27 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

Archivos guardados:
- experiments\cnn_full_4_aug_minimal_fold_results.csv
- experiments\cnn_full_4_aug_minimal_history.csv
- experiments\cnn_full_4_aug_minimal_summary.json
- results\training_curves\cnn_full_4_aug_minimal_loss.png
- results\training_curves\cnn_full_4_aug_minimal_accuracy.png
- results\confusion_matrices\cnn_full_4_aug_minimal.png
- results\classification_reports\cnn_full_4_aug_minimal_classification_report.txt

================================================================================
Corriendo FULL CV: CNN_FULL_6_weight_decay_1e3
================================================================================
Device usado: cpu
Folds a correr: [0, 1, 2, 3, 4]
Clases: {0: 'Actinic keratosis', 1: 'Atopic Dermatitis', 2: 'Benign keratosis', 3: 'Dermatofibroma', 4: 'Melanocytic nevus', 5: 'Melanoma', 6: 'Squamous cell carcinoma', 7: 'Tinea Ringworm Candidiasis', 8: 'Vascular lesion'}
Parámetros entrenables: 2,736,009
[CNN_FULL_6_weight_decay_1e3] fold 0 | epoch 01/25 | train_acc=0.215 | val_acc=0.347 | val_f1=0.267
[CNN_FULL_6_weight_decay_1e3] fold 0 | epoch 02/25 | train_acc=0.321 | val_acc=0.438 | val_f1=0.359
[CNN_FULL_6_weight_decay_1e3] fold 0 | epoch 03/25 | train_acc=0.394 | val_acc=0.354 | val_f1=0.293
[CNN_FULL_6_weight_decay_1e3] fold 0 | epoch 04/25 | train_acc=0.468 | val_acc=0.472 | val_f1=0.437
[CNN_FULL_6_weight_decay_1e3] fold 0 | epoch 05/25 | train_acc=0.473 | val_acc=0.590 | val_f1=0.561
[CNN_FULL_6_weight_decay_1e3] fold 0 | epoch 06/25 | train_acc=0.515 | val_acc=0.583 | val_f1=0.538
[CNN_FULL_6_weight_decay_1e3] fold 0 | epoch 07/25 | train_acc=0.511 | val_acc=0.639 | val_f1=0.596
[CNN_FULL_6_weight_decay_1e3] fold 0 | epoch 08/25 | train_acc=0.538 | val_acc=0.556 | val_f1=0.528
[CNN_FULL_6_weight_decay_1e3] fold 0 | epoch 09/25 | train_acc=0.569 | val_acc=0.583 | val_f1=0.540
[CNN_FULL_6_weight_decay_1e3] fold 0 | epoch 10/25 | train_acc=0.558 | val_acc=0.562 | val_f1=0.545
[CNN_FULL_6_weight_decay_1e3] fold 0 | epoch 11/25 | train_acc=0.558 | val_acc=0.618 | val_f1=0.588
[CNN_FULL_6_weight_decay_1e3] fold 0 | epoch 12/25 | train_acc=0.599 | val_acc=0.611 | val_f1=0.589
[CNN_FULL_6_weight_decay_1e3] fold 0 | epoch 13/25 | train_acc=0.609 | val_acc=0.604 | val_f1=0.564
Early stopping en fold 0. Mejor epoch: 7, mejor val_acc: 0.639
[CNN_FULL_6_weight_decay_1e3] fold 1 | epoch 01/25 | train_acc=0.234 | val_acc=0.285 | val_f1=0.233
[CNN_FULL_6_weight_decay_1e3] fold 1 | epoch 02/25 | train_acc=0.346 | val_acc=0.340 | val_f1=0.285
[CNN_FULL_6_weight_decay_1e3] fold 1 | epoch 03/25 | train_acc=0.356 | val_acc=0.444 | val_f1=0.378
[CNN_FULL_6_weight_decay_1e3] fold 1 | epoch 04/25 | train_acc=0.403 | val_acc=0.486 | val_f1=0.432
[CNN_FULL_6_weight_decay_1e3] fold 1 | epoch 05/25 | train_acc=0.468 | val_acc=0.451 | val_f1=0.391
[CNN_FULL_6_weight_decay_1e3] fold 1 | epoch 06/25 | train_acc=0.520 | val_acc=0.528 | val_f1=0.504
[CNN_FULL_6_weight_decay_1e3] fold 1 | epoch 07/25 | train_acc=0.497 | val_acc=0.472 | val_f1=0.401
[CNN_FULL_6_weight_decay_1e3] fold 1 | epoch 08/25 | train_acc=0.487 | val_acc=0.556 | val_f1=0.537
[CNN_FULL_6_weight_decay_1e3] fold 1 | epoch 09/25 | train_acc=0.560 | val_acc=0.535 | val_f1=0.487
[CNN_FULL_6_weight_decay_1e3] fold 1 | epoch 10/25 | train_acc=0.572 | val_acc=0.542 | val_f1=0.507
[CNN_FULL_6_weight_decay_1e3] fold 1 | epoch 11/25 | train_acc=0.590 | val_acc=0.583 | val_f1=0.574
[CNN_FULL_6_weight_decay_1e3] fold 1 | epoch 12/25 | train_acc=0.579 | val_acc=0.597 | val_f1=0.581
[CNN_FULL_6_weight_decay_1e3] fold 1 | epoch 13/25 | train_acc=0.574 | val_acc=0.576 | val_f1=0.538
[CNN_FULL_6_weight_decay_1e3] fold 1 | epoch 14/25 | train_acc=0.616 | val_acc=0.660 | val_f1=0.653
[CNN_FULL_6_weight_decay_1e3] fold 1 | epoch 15/25 | train_acc=0.581 | val_acc=0.542 | val_f1=0.523
[CNN_FULL_6_weight_decay_1e3] fold 1 | epoch 16/25 | train_acc=0.607 | val_acc=0.639 | val_f1=0.626
[CNN_FULL_6_weight_decay_1e3] fold 1 | epoch 17/25 | train_acc=0.613 | val_acc=0.639 | val_f1=0.612
[CNN_FULL_6_weight_decay_1e3] fold 1 | epoch 18/25 | train_acc=0.635 | val_acc=0.618 | val_f1=0.590
[CNN_FULL_6_weight_decay_1e3] fold 1 | epoch 19/25 | train_acc=0.614 | val_acc=0.618 | val_f1=0.616
[CNN_FULL_6_weight_decay_1e3] fold 1 | epoch 20/25 | train_acc=0.613 | val_acc=0.562 | val_f1=0.525
Early stopping en fold 1. Mejor epoch: 14, mejor val_acc: 0.660
[CNN_FULL_6_weight_decay_1e3] fold 2 | epoch 01/25 | train_acc=0.221 | val_acc=0.336 | val_f1=0.278
[CNN_FULL_6_weight_decay_1e3] fold 2 | epoch 02/25 | train_acc=0.354 | val_acc=0.413 | val_f1=0.344
[CNN_FULL_6_weight_decay_1e3] fold 2 | epoch 03/25 | train_acc=0.397 | val_acc=0.462 | val_f1=0.427
[CNN_FULL_6_weight_decay_1e3] fold 2 | epoch 04/25 | train_acc=0.497 | val_acc=0.538 | val_f1=0.473
[CNN_FULL_6_weight_decay_1e3] fold 2 | epoch 05/25 | train_acc=0.491 | val_acc=0.524 | val_f1=0.510
[CNN_FULL_6_weight_decay_1e3] fold 2 | epoch 06/25 | train_acc=0.516 | val_acc=0.566 | val_f1=0.560
[CNN_FULL_6_weight_decay_1e3] fold 2 | epoch 07/25 | train_acc=0.533 | val_acc=0.587 | val_f1=0.538
[CNN_FULL_6_weight_decay_1e3] fold 2 | epoch 08/25 | train_acc=0.573 | val_acc=0.517 | val_f1=0.482
[CNN_FULL_6_weight_decay_1e3] fold 2 | epoch 09/25 | train_acc=0.563 | val_acc=0.552 | val_f1=0.523
[CNN_FULL_6_weight_decay_1e3] fold 2 | epoch 10/25 | train_acc=0.556 | val_acc=0.573 | val_f1=0.551
[CNN_FULL_6_weight_decay_1e3] fold 2 | epoch 11/25 | train_acc=0.557 | val_acc=0.601 | val_f1=0.581
[CNN_FULL_6_weight_decay_1e3] fold 2 | epoch 12/25 | train_acc=0.591 | val_acc=0.573 | val_f1=0.557
[CNN_FULL_6_weight_decay_1e3] fold 2 | epoch 13/25 | train_acc=0.632 | val_acc=0.594 | val_f1=0.561
[CNN_FULL_6_weight_decay_1e3] fold 2 | epoch 14/25 | train_acc=0.622 | val_acc=0.573 | val_f1=0.550
[CNN_FULL_6_weight_decay_1e3] fold 2 | epoch 15/25 | train_acc=0.610 | val_acc=0.629 | val_f1=0.617
[CNN_FULL_6_weight_decay_1e3] fold 2 | epoch 16/25 | train_acc=0.657 | val_acc=0.580 | val_f1=0.558
[CNN_FULL_6_weight_decay_1e3] fold 2 | epoch 17/25 | train_acc=0.671 | val_acc=0.566 | val_f1=0.562
[CNN_FULL_6_weight_decay_1e3] fold 2 | epoch 18/25 | train_acc=0.632 | val_acc=0.587 | val_f1=0.574
[CNN_FULL_6_weight_decay_1e3] fold 2 | epoch 19/25 | train_acc=0.639 | val_acc=0.601 | val_f1=0.605
[CNN_FULL_6_weight_decay_1e3] fold 2 | epoch 20/25 | train_acc=0.652 | val_acc=0.636 | val_f1=0.619
[CNN_FULL_6_weight_decay_1e3] fold 2 | epoch 21/25 | train_acc=0.664 | val_acc=0.594 | val_f1=0.581
[CNN_FULL_6_weight_decay_1e3] fold 2 | epoch 22/25 | train_acc=0.672 | val_acc=0.615 | val_f1=0.596
[CNN_FULL_6_weight_decay_1e3] fold 2 | epoch 23/25 | train_acc=0.706 | val_acc=0.601 | val_f1=0.590
[CNN_FULL_6_weight_decay_1e3] fold 2 | epoch 24/25 | train_acc=0.702 | val_acc=0.594 | val_f1=0.581
[CNN_FULL_6_weight_decay_1e3] fold 2 | epoch 25/25 | train_acc=0.714 | val_acc=0.580 | val_f1=0.569
[CNN_FULL_6_weight_decay_1e3] fold 3 | epoch 01/25 | train_acc=0.197 | val_acc=0.378 | val_f1=0.320
[CNN_FULL_6_weight_decay_1e3] fold 3 | epoch 02/25 | train_acc=0.328 | val_acc=0.406 | val_f1=0.366
[CNN_FULL_6_weight_decay_1e3] fold 3 | epoch 03/25 | train_acc=0.390 | val_acc=0.483 | val_f1=0.434
[CNN_FULL_6_weight_decay_1e3] fold 3 | epoch 04/25 | train_acc=0.429 | val_acc=0.531 | val_f1=0.492
[CNN_FULL_6_weight_decay_1e3] fold 3 | epoch 05/25 | train_acc=0.474 | val_acc=0.531 | val_f1=0.488
[CNN_FULL_6_weight_decay_1e3] fold 3 | epoch 06/25 | train_acc=0.507 | val_acc=0.517 | val_f1=0.485
[CNN_FULL_6_weight_decay_1e3] fold 3 | epoch 07/25 | train_acc=0.517 | val_acc=0.524 | val_f1=0.489
[CNN_FULL_6_weight_decay_1e3] fold 3 | epoch 08/25 | train_acc=0.570 | val_acc=0.580 | val_f1=0.569
[CNN_FULL_6_weight_decay_1e3] fold 3 | epoch 09/25 | train_acc=0.573 | val_acc=0.531 | val_f1=0.504
[CNN_FULL_6_weight_decay_1e3] fold 3 | epoch 10/25 | train_acc=0.592 | val_acc=0.580 | val_f1=0.543
[CNN_FULL_6_weight_decay_1e3] fold 3 | epoch 11/25 | train_acc=0.563 | val_acc=0.573 | val_f1=0.558
[CNN_FULL_6_weight_decay_1e3] fold 3 | epoch 12/25 | train_acc=0.615 | val_acc=0.559 | val_f1=0.492
[CNN_FULL_6_weight_decay_1e3] fold 3 | epoch 13/25 | train_acc=0.610 | val_acc=0.566 | val_f1=0.559
[CNN_FULL_6_weight_decay_1e3] fold 3 | epoch 14/25 | train_acc=0.601 | val_acc=0.608 | val_f1=0.596
[CNN_FULL_6_weight_decay_1e3] fold 3 | epoch 15/25 | train_acc=0.627 | val_acc=0.636 | val_f1=0.603
[CNN_FULL_6_weight_decay_1e3] fold 3 | epoch 16/25 | train_acc=0.639 | val_acc=0.580 | val_f1=0.563
[CNN_FULL_6_weight_decay_1e3] fold 3 | epoch 17/25 | train_acc=0.624 | val_acc=0.622 | val_f1=0.592
[CNN_FULL_6_weight_decay_1e3] fold 3 | epoch 18/25 | train_acc=0.681 | val_acc=0.601 | val_f1=0.602
[CNN_FULL_6_weight_decay_1e3] fold 3 | epoch 19/25 | train_acc=0.666 | val_acc=0.622 | val_f1=0.601
[CNN_FULL_6_weight_decay_1e3] fold 3 | epoch 20/25 | train_acc=0.692 | val_acc=0.608 | val_f1=0.594
[CNN_FULL_6_weight_decay_1e3] fold 3 | epoch 21/25 | train_acc=0.695 | val_acc=0.622 | val_f1=0.599
Early stopping en fold 3. Mejor epoch: 15, mejor val_acc: 0.636
[CNN_FULL_6_weight_decay_1e3] fold 4 | epoch 01/25 | train_acc=0.268 | val_acc=0.406 | val_f1=0.348
[CNN_FULL_6_weight_decay_1e3] fold 4 | epoch 02/25 | train_acc=0.366 | val_acc=0.434 | val_f1=0.387
[CNN_FULL_6_weight_decay_1e3] fold 4 | epoch 03/25 | train_acc=0.416 | val_acc=0.517 | val_f1=0.465
[CNN_FULL_6_weight_decay_1e3] fold 4 | epoch 04/25 | train_acc=0.463 | val_acc=0.545 | val_f1=0.480
[CNN_FULL_6_weight_decay_1e3] fold 4 | epoch 05/25 | train_acc=0.484 | val_acc=0.552 | val_f1=0.518
[CNN_FULL_6_weight_decay_1e3] fold 4 | epoch 06/25 | train_acc=0.519 | val_acc=0.545 | val_f1=0.500
[CNN_FULL_6_weight_decay_1e3] fold 4 | epoch 07/25 | train_acc=0.547 | val_acc=0.552 | val_f1=0.522
[CNN_FULL_6_weight_decay_1e3] fold 4 | epoch 08/25 | train_acc=0.554 | val_acc=0.615 | val_f1=0.626
[CNN_FULL_6_weight_decay_1e3] fold 4 | epoch 09/25 | train_acc=0.547 | val_acc=0.573 | val_f1=0.580
[CNN_FULL_6_weight_decay_1e3] fold 4 | epoch 10/25 | train_acc=0.577 | val_acc=0.594 | val_f1=0.591
[CNN_FULL_6_weight_decay_1e3] fold 4 | epoch 11/25 | train_acc=0.563 | val_acc=0.545 | val_f1=0.527
[CNN_FULL_6_weight_decay_1e3] fold 4 | epoch 12/25 | train_acc=0.561 | val_acc=0.573 | val_f1=0.562
[CNN_FULL_6_weight_decay_1e3] fold 4 | epoch 13/25 | train_acc=0.584 | val_acc=0.608 | val_f1=0.608
[CNN_FULL_6_weight_decay_1e3] fold 4 | epoch 14/25 | train_acc=0.601 | val_acc=0.580 | val_f1=0.574
Early stopping en fold 4. Mejor epoch: 8, mejor val_acc: 0.615

2026/06/18 12:22:19 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

Archivos guardados:
- experiments\cnn_full_6_weight_decay_1e3_fold_results.csv
- experiments\cnn_full_6_weight_decay_1e3_history.csv
- experiments\cnn_full_6_weight_decay_1e3_summary.json
- results\training_curves\cnn_full_6_weight_decay_1e3_loss.png
- results\training_curves\cnn_full_6_weight_decay_1e3_accuracy.png
- results\confusion_matrices\cnn_full_6_weight_decay_1e3.png
- results\classification_reports\cnn_full_6_weight_decay_1e3_classification_report.txt

,experiment,model,dropout,batch_norm,weight_decay,lr,augmentation,val_accuracy_mean,val_accuracy_std,val_macro_f1_mean,val_balanced_accuracy_mean
0,CNN_FULL_4_aug_minimal,AlexNetSmall,0.3,True,0.0001,0.0003,minimal,0.679157,0.020665,0.673943,0.673236
1,CNN_FULL_6_weight_decay_1e3,AlexNetSmall,0.3,True,0.0010,0.0003,light,0.637345,0.014052,0.619341,0.627523

In [8]:
baseline_summary_path = Path("experiments/cnn_0_alexnetsmall_bn_dropout_wd_lightaug_summary.json")

with open(baseline_summary_path, "r", encoding="utf-8") as f:
    baseline_summary = json.load(f)

baseline_row = {
    "experiment": baseline_summary["experiment"],
    "model": baseline_summary["model"],
    "dropout": baseline_summary["dropout"],
    "batch_norm": baseline_summary["batch_norm"],
    "weight_decay": baseline_summary["weight_decay"],
    "lr": baseline_summary["lr"],
    "augmentation": baseline_summary["augmentation"],
    "val_accuracy_mean": baseline_summary["val_accuracy_mean"],
    "val_accuracy_std": baseline_summary["val_accuracy_std"],
    "val_macro_f1_mean": baseline_summary["val_macro_f1_mean"],
    "val_balanced_accuracy_mean": baseline_summary["val_balanced_accuracy_mean"],
}

comparison_cnn_df = pd.concat(
    [
        pd.DataFrame([baseline_row]),
        full_df[[
            "experiment",
            "model",
            "dropout",
            "batch_norm",
            "weight_decay",
            "lr",
            "augmentation",
            "val_accuracy_mean",
            "val_accuracy_std",
            "val_macro_f1_mean",
            "val_balanced_accuracy_mean",
        ]],
    ],
    ignore_index=True,
)

comparison_cnn_df = comparison_cnn_df.sort_values("val_accuracy_mean", ascending=False)

display(comparison_cnn_df)

,experiment,model,dropout,batch_norm,weight_decay,lr,augmentation,val_accuracy_mean,val_accuracy_std,val_macro_f1_mean,val_balanced_accuracy_mean
1,CNN_FULL_4_aug_minimal,AlexNetSmall,0.3,True,0.0001,0.0003,minimal,0.679157,0.020665,0.673943,0.673236
0,CNN_0_alexnetsmall_bn_dropout_wd_lightaug,AlexNetSmall,0.3,True,0.0001,0.0003,light,0.644318,0.021674,0.632304,0.639593
2,CNN_FULL_6_weight_decay_1e3,AlexNetSmall,0.3,True,0.0010,0.0003,light,0.637345,0.014052,0.619341,0.627523

In [9]:
comparison_cnn_path = Path("experiments/cnn_full_comparison.csv")
comparison_cnn_df.to_csv(comparison_cnn_path, index=False)
print("Guardado:", comparison_cnn_path)

Guardado: experiments\cnn_full_comparison.csv